---
body_model:
  gender: neutral
  bm_fname: ../../../../support_data/dowloads/models/smplx/neutral/model.npz

general:
  verbosity: 0
  expr_id:
  dataset_id: SFU_test
  rnd_seed: 100
  work_basedir: ../../../../support_data/training/training_experiments
  dataset_basedir: ../../../../AMASS/DataSet

logging:
  expr_msg:
  num_bodies_to_display: 4
  work_dir:
  dataset_dir:
  render_during_training: False
  best_model_fname:

train_parms:
  batch_size: 32
  num_epochs: 20
  restore_optimizer: False
  gen_optimizer:
    type: Adam
    args:
      lr: 0.0001
      weight_decay: 0.00001
  gradient_clip_val: 1.0
  lr_scheduler:
    type: ReduceLROnPlateau
    args:
      verbose: true
      patience: 1
  early_stopping:
    monitor: val_loss
    min_delta: 0.0
    patience: 2
    verbose: True
    mode: min
  keep_extra_loss_terms_until_epoch: 15
  loss_weights:
    loss_kl_wt: 0.005
    loss_rec_wt: 4
    loss_matrot_wt: 2
    loss_jtr_wt: 2

data_parms:
  num_workers: 0
  amass_dir: ../../../../AMASS
  num_timeseq_frames: 1
  amass_splits:
    vald:
      - SFU
    train:
      - SFU
    test:
      - SFU

model_params:
  num_neurons : 512
  latentD : 32
